export const sharedObject = {
  user: {
    userId: "",
    mail: "",
    firstName: "",
    lastName: "",
    birthday: "",
    password: "",
    logInStatus: true,
    createdOn: "",
    lastLoggedIn: "",
    browsedTopics: [],
    numberOfBrowsedTopics: 0,
  },
  topicsArray: [
    {
      title: "NoSQL Databases",
      description: "Introduction to NoSQL databases, including types such as MongoDB, Cassandra, and Redis. Learn about their use cases and advantages over relational databases.",
      url: "https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path?sessionFields=%5B%5B%22introduction%22%2C%22Foundational%22%5D%5D",
      image: "images/1_9wiBoMLVv43wwJmB0EIjLg.png",
      numberOfVisits: 0,
      tag: "NoSQL",
      topicPage: "/topic1.html",
    },
    {
      title: "Relational Databases",
      description: "Explore relational databases such as MySQL, PostgreSQL, and SQL Server. Learn about the structured data model, SQL queries, and data normalization.",
      url: "https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path?sessionFields=%5B%5B%22introduction%22%2C%22Foundational%22%5D%5D",
      image: "images/0712-Bad_Practices_in_Database_Design_-_Are_You_Making_These_Mistakes_Dan_Social.png",
      numberOfVisits: 0,
      tag: "SQL",
      topicPage: "/topic1.html",
    },
    {
      title: "Database Indexing",
      description: "Learn about indexing strategies to optimize query performance in both SQL and NoSQL databases. Covers B-trees, hash indexes, and full-text search.",
      url: "https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path?sessionFields=%5B%5B%22introduction%22%2C%22Foundational%22%5D%5D",
      image: "images/1_bRozPaCjzU_naiijFM6vxg.png",
      numberOfVisits: 0,
      tag: "Databases",
      topicPage: "/topic1.html",
    },
  ],
};
